"""add timestamps to custom_meals

Revision ID: 5814e373463e
Revises: bae8bfc6d5dd
Create Date: 2025-12-07 00:59:43.473703+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5814e373463e'
down_revision: Union[str, None] = 'bae8bfc6d5dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_meal_items', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('custom_meals', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('custom_meals', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_meals', 'updated_at')
    op.drop_column('custom_meals', 'created_at')
    op.drop_column('custom_meal_items', 'created_at')
    # ### end Alembic commands ###
