"""add custom meal and custom meal item tables

Revision ID: bae8bfc6d5dd
Revises: 501d978e3a63
Create Date: 2025-12-07 00:53:58.655408+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bae8bfc6d5dd'
down_revision: Union[str, None] = '501d978e3a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_meals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_meals_user_id'), 'custom_meals', ['user_id'], unique=False)
    op.create_table('custom_meal_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['food_id'], ['food_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meal_id'], ['custom_meals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_meal_items_meal_id'), 'custom_meal_items', ['meal_id'], unique=False)
    op.drop_index(op.f('ix_custom_foods_user_id'), table_name='custom_foods')
    op.drop_constraint(op.f('custom_foods_user_id_fkey'), 'custom_foods', type_='foreignkey')
    op.create_foreign_key(None, 'custom_foods', 'users', ['user_id'], ['id'])
    op.drop_column('custom_foods', 'updated_at')
    op.drop_column('custom_foods', 'created_at')
    op.drop_index(op.f('ix_daily_goals_user_id'), table_name='daily_goals')
    op.drop_column('daily_goals', 'updated_at')
    op.drop_column('daily_goals', 'created_at')
    op.drop_index(op.f('ix_diary_entries_user_date'), table_name='diary_entries')
    op.drop_constraint(op.f('uq_user_category_name'), 'meal_categories', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_category_name'), 'meal_categories', ['user_id', 'name'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_diary_entries_user_date'), 'diary_entries', ['user_id', 'entry_date'], unique=False)
    op.add_column('daily_goals', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('daily_goals', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_daily_goals_user_id'), 'daily_goals', ['user_id'], unique=True)
    op.add_column('custom_foods', sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('custom_foods', sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'custom_foods', type_='foreignkey')
    op.create_foreign_key(op.f('custom_foods_user_id_fkey'), 'custom_foods', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_custom_foods_user_id'), 'custom_foods', ['user_id'], unique=False)
    op.drop_index(op.f('ix_custom_meal_items_meal_id'), table_name='custom_meal_items')
    op.drop_table('custom_meal_items')
    op.drop_index(op.f('ix_custom_meals_user_id'), table_name='custom_meals')
    op.drop_table('custom_meals')
    # ### end Alembic commands ###
